### ISSUE TITLE
Subreddits page

### ISSUE THREAD

**Issue by developers-github** [spikecodes/libreddit#183] opened 2021-04-07 15:44 UTC

**Comment by spikecodes** [comment] 2021-04-07 15:53
Hi, are you able to provide more context? Libreddit currently supports searching for subreddits along with searching for posts inside specific subreddits so I'm not sure what you mean.

**Comment by developers-github** [comment] 2021-04-07 20:03
I mean a dedicated tab/page for searching subreddits and showing them even if they have graphic content (like violence)

**Comment by spikecodes** [comment] 2021-04-08 00:55
I'm having difficulty understanding what you mean. Is this feature currently available in Reddit? If so, are you able to send a screenshot of the functionality at Reddit?

**Comment by bnainar** [comment] 2021-04-08 11:19
He/she may mean like a dedicated page to search from, apart from searching from that search box inside a subreddit page. Like GitHub has, github.com/search

You consider implementing, if you want to add a advanced search option

**Comment by developers-github** [comment] 2021-04-08 12:47
Thank you @bnainar

**Comment by spikecodes** [comment] 2021-04-20 04:25
I see, thanks!

**Comment by spikecodes** [comment] 2021-05-05 19:15
I realise this is a duplicate of #125 so I'll close this issue and redirect discussion there.

**Closed by spikecodes** 2021-05-05 19:15 UTC
Labels: enhancement
