### ISSUE TITLE
RSS/Atom export

### ISSUE THREAD

**Issue by erdnaxe** [spikecodes/libreddit#190] opened 2021-04-11 16:38 UTC
## Is your feature request related to a problem? Please describe.
I would like to be able to fetch content using RSS/Atom feeds.

## Describe the solution you'd like
For example I would like `/r/sub_reddit.rss` to be the RSS feed of `/r/sub_reddit/`, just like the official Reddit instance.

## Describe alternatives you've considered
Parsing libreddit HTML content with RSS-bridge.

## Additional context
/

**Comment by spikecodes** [comment] 2021-04-11 19:34
Duplicate of #27

**Closed** 2021-04-11 19:33 UTC
Labels: enhancement
