### ISSUE TITLE
gifs are not available on iOS

### ISSUE THREAD

**Issue by tenleftfingers** [spikecodes/libreddit#205] opened 2021-04-23 19:28 UTC
gifs and videos do not render on mobile browsers on iOS (Firefox / Safari). The problem happens with libredd.it but not reddit.com on the same device/browser(s).

## To reproduce
visit a url such as libredd.it/r/gifs on these browsers on iOS (iPhone 8 here) and notice that instead of gifs, you will only see default thumbnail. Example:
![photo_2021-04-23 20 24 00](https://user-images.githubusercontent.com/1757768/115920411-0f02c980-a472-11eb-9e05-174b5375ea55.jpeg)

I can view and loop the gifs by instead visiting reddit.com/r/gifs

(great work on this project by the way, thank you!)

**Comment by Mennaruuk** [comment] 2021-04-23 23:40
Duplicate #76

**Comment by spikecodes** [comment] 2021-04-24 04:06
Thanks for opening this bug report! Mennaruuk appears to be right, this looks like a duplicate of that issue.

I'm happy that you like the project! :)

**Closed by spikecodes** 2021-04-24 04:06 UTC
Labels: bug
