### ISSUE TITLE
Login And Access Reddit.com Account?

### ISSUE THREAD

**Issue by trymeouteh** [spikecodes/libreddit#426] opened 2022-02-14 03:52 UTC
The ability to login to your reddit account and be able to post, vote, subscribe to subreddits, etc.

**Comment by TheCultLeader666** [comment] 2022-03-01 12:56
I might say this is a duplicate of #229

more info in this comment: https://github.com/spikecodes/libreddit/issues/229#issuecomment-880099641

**Closed** 2022-03-14 00:53 UTC
Labels: feature parity
