### ISSUE TITLE
Couldn't send request to Reddit: CertNotValidForName

### ISSUE THREAD

**Issue by megascrapper** [spikecodes/libreddit#193] opened 2021-04-14 05:38 UTC
## Describe the bug

I just pulled the docker image for ARM so I can deploy it on my raspberry pi, but while the container starts every page that I visit returns this error message: `Couldn't send request to Reddit: error trying to connect: invalid certificate: CertNotValidForName` and the page itself returns a 404 response.

## To reproduce

1. Deploy the docker image as described in README
2. Access libreddit for any reddit url
## Expected behavior

It should load a page that mirrors reddit

## Additional context

OS: Raspberry Pi OS 64-bit
Device: Raspberry Pi 4

**Comment by spikecodes** [comment] 2021-04-15 04:50
Thanks for reporting this bug! I have just realized that certificates were not being properly loaded in the ARM Dockerfile. This [should be fixed now](https://github.com/spikecodes/libreddit/commit/46e22cf74e16b4a8b966e8f2302832dba72987d6), feel free to reopen this issue if the problem persists!

**Comment by megascrapper** [comment] 2021-04-15 10:45
I'm still getting the same error even after pulling the latest image v0.10.3. I tried checking the docker logs but there's really nothing of interest.
```
$ docker logs libreddit
Starting Libreddit...
Running Libreddit v0.10.3 on 0.0.0.0:8080!
```

**Comment by spikecodes** [comment] 2021-04-15 16:37
Sorry to hear that, I will attempt to reproduce this issue on a Raspberry Pi 3b.

**Comment by spikecodes** [comment] 2021-04-18 01:43
Are you able to confirm this was on the `arm` tag?

**Comment by spikecodes** [comment] 2021-04-18 04:33
In order to run correctly on Raspberry Pi 2s, RPi 3s, or RPi 4s, the Docker GitHub Action workflow should build for the armv7 architecture. Unfortunately, I was not able to do this because I ran into [this issue](https://github.com/docker/buildx/issues/395) with Docker Buildx.

**Comment by spikecodes** [comment] 2021-05-21 15:43
Libreddit currently has no armv7 build so I'll be closing this issue in favor of #221.

**Closed by spikecodes** 2021-05-21 15:43 UTC
Labels: bug
