### ISSUE TITLE
Please add indexing settings.

### ISSUE THREAD

**Issue by walkxcode** [spikecodes/libreddit#463] opened 2022-03-25 01:01 UTC
I'm currently being hit with millions of requests from Bing every 15 minutes because it is indexing my entire libreddit instance. Please add settings to block indexing.

**Comment by spikecodes** [comment] 2022-03-26 19:51
Duplicate of https://github.com/spikecodes/libreddit/issues/265

**Closed by spikecodes** 2022-03-26 19:51 UTC
Labels: enhancement
