### ISSUE TITLE
RSS feed(s) for followed users and subscribed subreddits.

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#225] opened 2021-05-23 09:28 UTC
## Describe the solution you'd like
Have an endpoint for RSS/Atom/etc feeds. Use the cookie as the URL param, so you can use it in your RSS reader.

**Comment by spikecodes** [comment] 2021-05-23 15:56
This looks to be a duplicate of https://github.com/spikecodes/libreddit/issues/27, closing for now.

**Closed by spikecodes** 2021-05-23 15:56 UTC
Labels: enhancement

**Comment by jtagcat** [comment] 2021-05-23 23:23
wth; for both issues, I searched wide, pardon

**Comment by spikecodes** [comment] 2021-05-23 23:32
No worries! GitHub Search can be a bit wonky in terms of results :sweat_smile:
