### ISSUE TITLE
🐛 Bug Report: Multireddit subscription broken when using a lot of subreddits

### ISSUE THREAD

**Issue by tiekoetter** [spikecodes/libreddit#492] opened 2022-04-22 11:51 UTC
## Describe the bug
A user send me his subscription list because he would get an error 502 when he clicked on the "Subscribe to Multireddit" button.

## Steps to reproduce the bug

1. Open https://libreddit.tiekoetter.com/r/2baka4you+3DS+ACBA+AbandonedPorn+AbruptChaos+AnimalCrossing+AnimalTextGifs+AskReddit+Awwducational+BLAHAJ+BPD+BPD4BPD+BPDArt+BPDandCHILL+Beavers+Birdswithhats+Bulldogs+Catswhoyell+Chiptune+ClanMalkavian+CoOpGaming+Cows+CozyPlaces+DCcomics+DadForAMinute+DigitalArt+DigitalPainting+Dinosaurs+Djungelskog+DrunkOrAKid+EarthPorn+Elona+Erik+FFXIVGlamours+FreeGameFindings+FuckYouImAShark+GFD+GODZILLA+GamerPals+Games+Gaming4Gamers+HandMadeInPrison+HeckThisIsWholesome+HumansBeingBros+HydroHomies+IAmA+IdiotsFightingThings+IdiotsNearlyDying+ImaginaryLeviathans+ImaginaryWastelands+ImpracticalArmour+InvertPets+ItalianGaming+Jaww+JoJoMemes+JustGuysBeingDudes+JustUnsubbed+KenM+LeftWingMaleAdvocates+MMFB+MaliciousCompliance+Mastodon+Metalocalypse+MisleadingPuddles+Nanithehell+Natureisbrutal+NonPoliticalTwitter+Otters+Owls+PartyParrot+PetTheDamnDog+PixelArt+PokemonRaps+ProperAnimalNames+PublicFreakout+RBI+Raccoons+RandomActsOfGaming+ReasonableFantasy+SS13+ShipwreckPorn+ShitPostCrusaders+Slytherin+SomeOrdinaryGmrs+Springtail+StardustCrusaders+StartledCats+StopBorderlineStigma+StopTouchingMe+StoppedWorking+Terraria+ThanksWorldGen+TheApexCollective+TheDepthsBelow+TheNineYearClub+TrueOffMyChest+TsundereSharks+Ultralight+UnexpectedThugLife+UpliftingNews+Wanted_raccoon+WhyWomenLiveLonger+WoWRolePlay+YouThinkYouDo+animearmor+ankmemes+armoredwomen+awoo+awwnverts+babyrhinogifs+batty+bears+bearsdoinghumanthings+bernesemountaindogs+bestofTLDR+birdswitharms+boop+bravelydefault+casualiama+catpranks+chiptunes+classicfallout+comicbooks+corgi+crabseatingthings+darknet+dogpictures+dogswithjobs+dreamhaven+europe+evilbuildings+explainlikeIAmA+facingtheirparenting+falloutlore+falloutnewvegas+firefly+fnv+fo3+foxes+gamernews+gametales+gamingsuggestions+giger+gravityfalls+harrypotter+hitmanimals+hpbookclub+hyenas+illegallysmolbirbs+isfj+italy+jojosbizzareadventure+learntodraw+linux4noobs+linuxquestions+monkslookingatbeer+monsterhunterclan+nanithefuck+natureismetal+nintendo+nocontext+nonononoyes+oceancreatures+oddlyterrifying+onetruegod+orangutan+outofcontextcomics+patientgamers+pcgaming+pixiedustcrusaders+pokemonwtf+rarepuppers+rpg+science+sharks+sharkswithhumanteeth+shiba+shouldercats+southpaws+spiderbro+spiders+splatoon+ss14+submechanophobia+terminal_porn+terrariaservers+tippytaps+togetheralone+tooktoomuch+transpositive+trashpandas+truegaming+truepixelart+u_IrisHopp+vtmb+whales+woof_irl+youseeingthisshit+zombiefortress
2. Click on "Subscribe to Multireddit"
3. Get an error 502 after about 15 seconds.

## What's the expected behavior?
Multireddit subscription should work as expected.

## Additional context / screenshot
https://libreddit.tiekoetter.com/r/2baka4you+3DS+ACBA+AbandonedPorn+AbruptChaos+AnimalCrossing+AnimalTextGifs+AskReddit+Awwducational+BLAHAJ+BPD+BPD4BPD+BPDArt+BPDandCHILL+Beavers+Birdswithhats+Bulldogs+Catswhoyell+Chiptune+ClanMalkavian+CoOpGaming+Cows+CozyPlaces+DCcomics+DadForAMinute+DigitalArt+DigitalPainting+Dinosaurs+Djungelskog+DrunkOrAKid+EarthPorn+Elona+Erik+FFXIVGlamours+FreeGameFindings+FuckYouImAShark+GFD+GODZILLA+GamerPals+Games+Gaming4Gamers+HandMadeInPrison+HeckThisIsWholesome+HumansBeingBros+HydroHomies+IAmA+IdiotsFightingThings+IdiotsNearlyDying+ImaginaryLeviathans+ImaginaryWastelands+ImpracticalArmour+InvertPets+ItalianGaming+Jaww+JoJoMemes+JustGuysBeingDudes+JustUnsubbed+KenM+LeftWingMaleAdvocates+MMFB+MaliciousCompliance+Mastodon+Metalocalypse+MisleadingPuddles+Nanithehell+Natureisbrutal+NonPoliticalTwitter+Otters+Owls+PartyParrot+PetTheDamnDog+PixelArt+PokemonRaps+ProperAnimalNames+PublicFreakout+RBI+Raccoons+RandomActsOfGaming+ReasonableFantasy+SS13+ShipwreckPorn+ShitPostCrusaders

This list works as expected. If you add one additional Subreddit it won't work.

It also happens on libredd.it

Not related to #122

**Comment by EdwardLangdon** [comment] 2022-04-23 08:27
I can verify this in another Instance too.

**Comment by azizLIGHT** [comment] 2022-04-25 16:16
This may be related to [#352 ](https://github.com/spikecodes/libreddit/issues/352#issuecomment-996935641)

**Comment by spikecodes** [comment] 2022-05-15 16:58
Closing as this is a duplicate of #352

**Closed by spikecodes** 2022-05-15 16:58 UTC
Labels: bug
